#!/bin/bash
USAGE="$0 khpy visualizer to launch run $0 with no args"
khmon=khmon/bin/khmon
khdb=khdb
khcfg=khs.cfg

if [[ $# != 0 ]]; then
  echo $USAGE > /dev/stderr
  exit 0
fi
 
binpath=$(readlink -n -f $0)
dirpath=$(dirname $binpath) 

#echo arg0=$0 binpath=$binpath dirpath=$dirpath

khmon=$dirpath/$khmon
khcfg=$dirpath/$khcfg
khdbdir=$(grep db_install_path= $khcfg)
khdbdir=${khdbdir##*=}

khdb=$khdbdir/$khdb

if [[ ! -d $khdb/Records/Node ]]; then
  echo "ERROR: $khdb does not seem to be a valid kh database" > /dev/stderr
  exit -1
fi

if [[ -x $khmon ]]; then
  exec $khmon LOCAL $khdb
else
  echo "ERROR: $khmon does not exist or is not executable" > /dev/stderr
  exit -1
fi
