#!/bin/bash
#set -x
HCMD=~/bin/khaas
KHHOSTDIR=/opt/khhosts
ts=/tmp/$$.ts
leasedir=/var/lib/dhcpd
node=$1

echo -n "Acquiring node from HAAS: " > /dev/stderr
start=$(date +%s)
ninfo=( $(${HCMD} acquire $node 2>/dev/stderr) )

if [[ $? != 0 ]]; then 
   echo "ERROR: no free nodes?"
   exit -1
fi

end=$(date +%s)
echo "$((end - start)) seconds" > /dev/stderr
total_start=$start
nname=${ninfo[0]}
nmac=${ninfo[1]}

if [[ -z $nname || -z $nmac ]]; then
  echo "ERROR: failed to get a node : $nname $nmac" > /dev/stderr
  exit -1
fi

echo "Got node: $nname mac; $mac" > /dev/stderr

if ls ${leasedir}/${nmac}_* > /dev/null 2>&1
then 
  echo "removing ${leasedir}/${nmac}_*"
  rm  ${leasedir}/${nmac}_*
fi

echo -n "Power cycling $nname: " >/dev/stderr
start=$(date +%s)
${HCMD} powerCycle $nname 2> /dev/stderr
end=$(date +%s)
echo "$((end - start)) seconds" > /dev/stderr

echo -n "waiting for node to boot:" > /dev/stderr

start=$(date +%s)
while ! ls ${leasedir}/${nmac}_* > /dev/null 2>&1; do 
  echo -n . >/dev/stderr
  sleep 5;
done
end=$(date +%s)
echo " $((end - start)) seconds" >/dev/stderr


nip=$(echo ${leasedir}/${nmac}_*)
nip=${nip##*_}

echo -n "waiting for salt to be ready on $nip:"
while ! salt-run manage.up | grep -q $nip; do
    echo -n . >/dev/stderr
    sleep 5;
done
end=$(date +%s)
echo " $((end - start)) seconds" > /dev/stderr
total_end=$end
echo "Total: $((total_end - total_start)) seconds" > /dev/stderr

[[ ! -d $KHOSTDIR ]] && mkdir -p $KHOSTDIR
if ls ${KHHOSTDIR}/${mac}_* > /dev/null 2>&1; then
  rm ${KHHOSTDIR}/${mac}_*
fi
touch ${KHHOSTDIR}/${mac}_${nip}_${name}

echo $nip $nmac $nname
