#!/bin/bash

ip=$1
node=$2


[[ -z $ip ]] && { echo "USAGE: khremove <ip> <node>"; exit -1; }

salt "$ip" system.halt

while (salt-run manage.up | grep $ip); do
  sleep 5;
  echo -n "."
done

if [[ -n $node ]]; then
  khaas release $node
fi
